### ISSUE TITLE
Convert jupyter-web-app rock to use multiple parts

### ISSUE THREAD

**Issue by i-chvets** [canonical/kubeflow-rocks#22]
# Description
Convert jupyter-web-app rock to use multiple parts.
Currently, singel part is used to build the rock. When integrating this ROCK, convert it to use multiple parts as suggested:
> split it to two parts one with npm one with python for frontend and backend ?

**Comment by i-chvets** [comment]
Jupyter Web App ROCK was re-designed to be multi-part ROCK.
The following PR has corresponding changhes: https://github.com/canonical/kubeflow-rocks/pull/42

**Comment by DnPlas** [comment]
Closed by #42
