### ISSUE TITLE
rocks versioning patterns are inconsistent

### ISSUE THREAD

**Issue by ca-scribner** [canonical/kubeflow-rocks#23]
Nominally, it looks like all rocks say they version with `version format: <KF-upstream-version>_<Charmed-KF-version>`, but there's disagreement on what `<Charmed-KF-version>` is.  For example:

* [v1.7.0_1](https://github.com/canonical/kubeflow-rocks/blob/e48ccea393cdbdf1532d444c45ad6356694b5bcf/admission-webhook/rockcraft.yaml#LL3C19-L3C79)
* [v1.7.0_22.04_1](https://github.com/canonical/kubeflow-rocks/blob/main/jupyter-pytorch-full/rockcraft.yaml#L10)

In my head, I'd also have expected the initial release of Charmed Kubeflow for 1.7 would have been `_0` rather than `_1`, but I don't know if that's something I've seen us use or just something I made up.  Might just be my expectation because much of the things we interact with are 0-indexed

**Comment by i-chvets** [comment]
This issue is from initial ROCKs development workshop.
Versioninig has been stadartized and defined in corresponding spec.
Closing.
